# Generated by Django 3.2.12 on 2022-09-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Categoría Activada/Categoría no activada'),
        ),
    ]
