# Generated by Django 4.1.1 on 2022-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=90, verbose_name='Título'),
        ),
    ]
